// Shared styling for book detail views, note lists, and progress controls.
import { StyleSheet } from "react-native";
import { COLORS, FONTS } from "../../constants/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  content: {
    flexGrow: 1,
    padding: 20,
    gap: 18,
  },
  back: {
    color: COLORS.textSecondary,
    marginBottom: 4,
  },
  card: {
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 16,
    gap: 12,
  },
  center: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
  },
  title: {
    fontFamily: FONTS.serifBold,
    fontSize: 22,
    color: COLORS.textPrimary,
  },
  subtitle: {
    fontFamily: FONTS.sans,
    fontSize: 16,
    color: COLORS.textSecondary,
  },
  meta: {
    fontFamily: FONTS.sans,
    fontSize: 12,
    color: COLORS.textSecondary,
  },
  sectionTitle: {
    fontFamily: FONTS.serifBold,
    fontSize: 18,
    color: COLORS.textPrimary,
  },
  detailTitle: {
    fontFamily: FONTS.serifBold,
    fontSize: 24,
    color: COLORS.textPrimary,
    textAlign: "center",
  },
  detailAuthor: {
    fontFamily: FONTS.sans,
    fontSize: 16,
    color: COLORS.textSecondary,
    textAlign: "center",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  metaRow: {
    flexDirection: "row",
    gap: 12,
    flexWrap: "wrap",
  },
  statusPill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
  },
  statusPillText: {
    fontFamily: FONTS.sansBold,
    fontSize: 12,
    color: COLORS.textSecondary,
    textTransform: "capitalize",
  },
  input: {
    minHeight: 80,
    borderBottomWidth: 1,
    borderColor: COLORS.border,
    paddingVertical: 12,
    color: COLORS.textPrimary,
    textAlignVertical: "top",
    fontFamily: FONTS.sans,
  },
  inputCompact: {
    minHeight: 44,
    paddingVertical: 10,
  },
  error: {
    color: "#b00020",
  },
  muted: {
    color: COLORS.textSecondary,
  },
  navButton: {
    backgroundColor: COLORS.accent,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.accent,
  },
  navButtonSecondary: {
    backgroundColor: COLORS.surface,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  navButtonText: {
    color: COLORS.textPrimary,
    fontFamily: FONTS.sansBold,
    fontSize: 16,
  },
  navButtonTextSecondary: {
    color: COLORS.textSecondary,
    fontFamily: FONTS.sansBold,
    fontSize: 16,
  },
  navButtonTextGhost: {
    color: COLORS.accent,
  },
  ghostButton: {
    backgroundColor: COLORS.surface,
    borderColor: COLORS.border,
    borderWidth: 1,
  },
  detailHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 4,
  },
  detailBack: {
    color: COLORS.accent,
    fontFamily: FONTS.sansBold,
    marginBottom: 6,
  },
  editCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: COLORS.accent,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.surface,
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  editCircleText: {
    color: COLORS.accent,
    fontFamily: FONTS.sansBold,
    fontSize: 16,
    lineHeight: 18,
    textAlign: "center",
    textAlignVertical: "center",
    includeFontPadding: false,
  },
  detailContent: {
    flexGrow: 1,
    paddingHorizontal: 32,
    paddingBottom: 32,
    gap: 18,
    alignItems: "center",
  },
  coverFrame: {
    width: 180,
    height: 260,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: COLORS.surface,
  },
  coverImage: {
    width: "100%",
    height: "100%",
  },
  coverPlaceholder: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.surface,
  },
  coverPlaceholderText: {
    color: COLORS.textSecondary,
    fontFamily: FONTS.serifBold,
    fontSize: 16,
  },
  detailTitleBlock: {
    gap: 6,
    alignItems: "center",
  },
  progressBlock: {
    width: "100%",
    gap: 10,
  },
  actionRow: {
    width: "100%",
    flexDirection: "column",
    gap: 12,
  },
  noteItem: {
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    paddingTop: 8,
    marginTop: 8,
  },
  noteMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 4,
  },
  noteDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
  },
  noteActions: {
    flexDirection: "row",
    gap: 12,
    marginTop: 6,
  },
  action: {
    color: COLORS.accent,
    fontFamily: FONTS.sansBold,
  },
  danger: {
    color: "#b00020",
  },
  noteText: {
    fontFamily: FONTS.sans,
    fontSize: 14,
    color: COLORS.textPrimary,
  },
  noteDate: {
    fontSize: 12,
    color: COLORS.textSecondary,
    marginTop: 4,
  },
  noteInput: {
    minHeight: 60,
  },
  noteBadge: {
    fontSize: 12,
    color: COLORS.textSecondary,
    marginTop: 4,
    fontFamily: FONTS.sansBold,
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  pageRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  chip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
  },
  chipSmall: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
  },
  chipActive: {
    backgroundColor: COLORS.accent,
    borderColor: COLORS.accent,
  },
  chipText: {
    color: COLORS.textSecondary,
    fontFamily: FONTS.sansBold,
  },
  chipTextActive: {
    color: COLORS.background,
  },
  notesHeader: {
    gap: 8,
  },
  progressBarShell: {
    height: 12,
    borderRadius: 12,
    backgroundColor: COLORS.border,
    overflow: "hidden",
  },
  progressBarShellLarge: {
    height: 14,
    borderRadius: 12,
    backgroundColor: COLORS.border,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: COLORS.accent,
  },
  progressRow: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
  },
  progressInput: {
    flex: 1,
    minHeight: 44,
  },
  pageInput: {
    flex: 0.4,
    minHeight: 44,
  },
  pageRowTight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    width: "100%",
  },
  pageUpdateCard: {
    width: "100%",
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 16,
    padding: 14,
    gap: 10,
  },
  floatingComposer: {
    position: "absolute",
    left: 0,
    right: 0,
    paddingHorizontal: 16,
  },
  floatingCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 14,
    gap: 12,
  },
  floatingShadow: {
    shadowColor: "#000",
    shadowOpacity: 0.4,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 10,
  },
  notesContent: {
    paddingBottom: 220,
  },
  editLink: {
    color: COLORS.accent,
    fontFamily: FONTS.sansBold,
    marginTop: 4,
  },
});
