// Styling for the search form, result card, and helper tips.
import { StyleSheet } from "react-native";
import { COLORS, FONTS } from "../../constants/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  content: {
    flexGrow: 1,
    padding: 20,
    gap: 18,
  },
  title: {
    fontFamily: FONTS.serifBold,
    fontSize: 26,
    textAlign: "center",
    color: COLORS.textPrimary,
  },
  subtitle: {
    fontFamily: FONTS.sans,
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: "center",
    lineHeight: 20,
  },
  input: {
    borderBottomWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 0,
    paddingVertical: 12,
    color: COLORS.textPrimary,
    fontFamily: FONTS.sans,
  },
  inputShell: {
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    paddingHorizontal: 12,
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  inputFlex: {
    flex: 1,
  },
  clearBtn: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  clearText: {
    color: COLORS.textSecondary,
    fontFamily: FONTS.sansBold,
    fontSize: 12,
  },
  navButton: {
    backgroundColor: COLORS.accent,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.accent,
  },
  navButtonText: {
    color: COLORS.textPrimary,
    fontFamily: FONTS.sansBold,
    fontSize: 16,
  },
  navButtonTextGhost: {
    color: COLORS.accent,
  },
  secondaryButton: {
    backgroundColor: COLORS.surface,
  },
  tertiaryButton: {
    backgroundColor: COLORS.accent,
  },
  navButtonTextAccent: {
    color: COLORS.accent,
    
  },
  ghostButton: {
    backgroundColor: COLORS.surface,
    borderColor: COLORS.border,
    paddingHorizontal: 14,
    borderRadius: 12,
  },
  iconGhostBtn: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  headerIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  navRow: {
    flexDirection: "row",
    gap: 8,
  },
  buttonRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  iconLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  status: {
    minHeight: 32,
    justifyContent: "center",
  },
  statusRow: {
    minHeight: 32,
    justifyContent: "center",
    gap: 6,
  },
  error: {
    color: "#b00020",
    marginTop: 8,
  },
  success: {
    color: COLORS.status.finished,
    marginTop: 8,
  },
  card: {
    backgroundColor: COLORS.surface,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    gap: 6,
  },
  cardPrimary: {
    backgroundColor: COLORS.surface,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    gap: 14,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  sectionTitle: {
    fontFamily: FONTS.serifBold,
    fontSize: 18,
    color: COLORS.textPrimary,
  },
  pill: {
    backgroundColor: COLORS.accent,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  pillText: {
    color: COLORS.background,
    fontFamily: FONTS.sansBold,
    fontSize: 12,
  },
  label: {
    fontSize: 12,
    color: COLORS.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    fontFamily: FONTS.sansBold,
  },
  value: {
    fontSize: 16,
    fontFamily: FONTS.sansBold,
    color: COLORS.textPrimary,
  },
  helper: {
    fontSize: 13,
    color: COLORS.textSecondary,
    fontFamily: FONTS.sans,
  },
  chipRow: {
    flexDirection: "row",
    gap: 10,
    flexWrap: "wrap",
  },
  chip: {
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  chipText: {
    color: COLORS.textSecondary,
    fontFamily: FONTS.sansBold,
    fontSize: 13,
  },
  cover: {
    width: 140,
    aspectRatio: 2 / 3,
    borderRadius: 8,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginTop: 6,
  },
  coverLarge: {
    width: 96,
    height: 144,
    borderRadius: 12,
    backgroundColor: COLORS.background,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  coverPlaceholder: {
    alignItems: "center",
    justifyContent: "center",
  },
  placeholder: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginTop: 6,
    fontFamily: FONTS.sans,
  },
  bookCard: {
    backgroundColor: COLORS.surface,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    gap: 12,
  },
  bookRow: {
    flexDirection: "row",
    gap: 14,
  },
  bookMeta: {
    flex: 1,
    gap: 6,
  },
  bookTitle: {
    fontFamily: FONTS.serifBold,
    fontSize: 18,
    color: COLORS.textPrimary,
  },
  bookAuthor: {
    fontFamily: FONTS.sans,
    fontSize: 14,
    color: COLORS.textSecondary,
  },
  bookIsbn: {
    fontFamily: FONTS.sansBold,
    fontSize: 12,
    color: COLORS.textSecondary,
  },
  sourcePill: {
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
  },
  sourceText: {
    color: COLORS.textSecondary,
    fontFamily: FONTS.sansBold,
    fontSize: 12,
  },
  tipCard: {
    backgroundColor: COLORS.surface,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    gap: 8,
  },
  linkInline: {
    color: COLORS.accent,
    textAlign: "left",
  },
});
